import { UnocssNuxtOptions } from "@unocss/nuxt";
import { transformerCompileClass } from "unocss";

export const unocss: UnocssNuxtOptions = {
  preflight: false,
  icons: true,
  webFonts: {
    fonts: {
      sans: [
        { name: "Inter", weights: [400, 600] },
        { name: "sans-serif", provider: "none" },
      ],
    },
  },
  theme: {
    darkMode: "class",
    breakpoints: {
      sm: "576px",
      md: "768px",
      lg: "992px",
      xl: "1200px",
      xxl: "1400px",
    },
    colors: {
      neutral: {
        DEFAULT: "var(--b-color-neutral-3)",
        "1": "var(--b-color-neutral-1)",
        "2": "var(--b-color-neutral-2)",
        "3": "var(--b-color-neutral-3)",
        "4": "var(--b-color-neutral-4)",
        "5": "var(--b-color-neutral-5)",
        "6": "var(--b-color-neutral-6)",
        "7": "var(--b-color-neutral-7)",
        "8": "var(--b-color-neutral-8)",
        "9": "var(--b-color-neutral-9)",
      },
      primary: {
        DEFAULT: "var(--b-color-primary-3)",
        "1": "var(--b-color-primary-1)",
        "2": "var(--b-color-primary-2)",
        "3": "var(--b-color-primary-3)",
        "4": "var(--b-color-primary-4)",
        "5": "var(--b-color-primary-5)",
      },
      blue: {
        DEFAULT: "var(--b-color-blue-3)",
        "1": "var(--b-color-blue-1)",
        "2": "var(--b-color-blue-2)",
        "3": "var(--b-color-blue-3)",
        "4": "var(--b-color-blue-4)",
        "5": "var(--b-color-blue-5)",
      },
      teal: {
        DEFAULT: "var(--b-color-teal-3)",
        "1": "var(--b-color-teal-1)",
        "2": "var(--b-color-teal-2)",
        "3": "var(--b-color-teal-3)",
        "4": "var(--b-color-teal-4)",
        "5": "var(--b-color-teal-5)",
      },
      green: {
        DEFAULT: "var(--b-color-green-3)",
        "1": "var(--b-color-green-1)",
        "2": "var(--b-color-green-2)",
        "3": "var(--b-color-green-3)",
        "4": "var(--b-color-green-4)",
        "5": "var(--b-color-green-5)",
      },
      yellow: {
        DEFAULT: "var(--b-color-yellow-3)",
        "1": "var(--b-color-yellow-1)",
        "2": "var(--b-color-yellow-2)",
        "3": "var(--b-color-yellow-3)",
        "4": "var(--b-color-yellow-4)",
        "5": "var(--b-color-yellow-5)",
      },
      orange: {
        DEFAULT: "var(--b-color-orange-3)",
        "1": "var(--b-color-orange-1)",
        "2": "var(--b-color-orange-2)",
        "3": "var(--b-color-orange-3)",
        "4": "var(--b-color-orange-4)",
        "5": "var(--b-color-orange-5)",
      },
      red: {
        DEFAULT: "var(--b-color-red-3)",
        "1": "var(--b-color-red-1)",
        "2": "var(--b-color-red-2)",
        "3": "var(--b-color-red-3)",
        "4": "var(--b-color-red-4)",
        "5": "var(--b-color-red-5)",
      },
    },
    boxShadow: {
      lv1: "var(--b-box-shadow-lv1)",
      lv2: "var(--b-box-shadow-lv2)",
      lv3: "var(--b-box-shadow-lv3)",
    },
    borderRadius: {
      "0": "0",
      max: "87rem",
      xs: "0.25rem",
      sm: "0.5rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.75rem",
    },
    fontSize: {
      xs: "10px",
      sm: "12px",
      base: "14px",
      lg: "16px",
      "2xl": "18px",
      "3xl": "20px",
      h4: "24px",
      h3: "28px",
      h2: "32px",
    },
  },
  shortcuts: [],
  variants: [],
  safelist: [],
  transformers: [transformerCompileClass()],
};
